name: my_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 3.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  walletconnect_flutter_v2: ^2.1.8
  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.11
  walletconnect_dart: ^0.0.11
  google_fonts: ^4.0.4
  slider_button: ^2.0.0
  web3dart: ^2.6.1
  flutter_web3: ^2.1.9
  flutter_stripe: ^9.5.0+1
  http: ^1.1.2
  expandable: ^5.0.1
  flutter_animate: ^4.5.0
  provider: ^6.1.1
 # web3modal_flutter: ^2.0.2
  image_network: ^2.5.4+1
  web3modal_flutter: ^3.0.1
  fl_toast: ^3.2.0
  syncfusion_flutter_charts: ^24.2.8



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true

assets:
  - assests/abis/
  - assets/abi.json


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/AppIcon.png"
